### PR TITLE
Enable named vectors uploading in `.upload_collection()` and retry logic

### LINKED ISSUE #114: `.upload_collection()` does not work with named vectors
For the initial upload, `QdrantClient.upload_collection()` should also work with named vectors, just as `.upload_records()`. A union over the current possible types and their dictionary counterparts should be implemented.

### PR DESCRIPTION
**Pull request by monatis**
Closes #114 and #115

### CODE REVIEW

**Comment by monatis** [comment]
Can I get a review here? @generall @joein

**Comment by joein** [comment]
@monatis I will review it tomorrow in the morning if you don't mind

**Comment by monatis** [comment]
Thanks @joein, sure.

**Review by generall — APPROVED** [review]
LGTM, but next time please do not combine multiple tasks and formatting changes into single PR

**Comment by monatis** [comment]
What about including an action for formatting just as we did in Quaterion.

**Comment by joein** [comment]
@monatis I am going to add black today

However, I am not sure whether it will be the same as in Quaterion. I might change something

**Pull request merged**
