### PR TITLE
Strip scheme from host parameter if provided when creating `QdrantClient` instance

### PR DESCRIPTION
**Pull request by nleroy917**
Details are in #88 

This just adds a helper function to the `QdrantClient` class that strips the [scheme](https://en.wikipedia.org/wiki/List_of_URI_schemes) from the hostname prior to self assigning the attribute and generating the `rest_uri`.

### CODE REVIEW

**Comment by generall** [comment]
Hi @nleroy917, thanks for the PR!

Would it be possible to try to avoid mixing of URL and Host concepts, as it could lead to misinterpretations?
For example, `https://localhost` parsed as URL should mean that we are intended to use 443 port and https protocol for communication. But code in the PR will discard this information without any warnings.

Would it be possible to make additional optional argument  `url`, which will be fully parsed into correct client configuration?

**Comment by nleroy917** [comment]
Sure. Do you mean sort of the paradigm that database connection libraries use? Where you can provide a connection string (`postgres://user:password@localhost:5432`) **or** the individual params (`host=localhost`, `password=...`, etc).

**Comment by generall** [comment]
> Sure. Do you mean sort of the paradigm that database connection libraries use? Where you can provide a connection string (`postgres://user:password@localhost:5432`) **or** the individual params (`host=localhost`, `password=...`, etc).
> 

Exactly! We could have additional optional parameter `url`, it it is provided, we can parse it into schema, port and host

**Comment by generall** [comment]
> Do you intend this to be in __init__ or in the new helper function on the class?

I think extending `__init__` will be reasonable

**Comment by nleroy917** [comment]
I'll work on this in the coming days. In the meantime, wondering if this flow seems reasonable for establishing the connection:

```mermaid
graph LR
  A[<code>__init__</code>] --> B{<code> url == None? </code>}
  B -- No --> C[Parse url into host and port]
  B -- Yes --> D[use provided host and port]
```

I also saw #92 I don't know if it's reasonable to add that functionality. But the diagram could be updated to look more like:

```mermaid
graph LR
  A[__init__] --> B{env vars?}
  B -- Yes --> C[connect with env vars]
  B -- No --> D{<code> url == None ? </code>}
  D -- No --> E[Parse url into host and port]
  D -- Yes --> F[use provided host and port]
```

I'm personally *opposed* to initiating from env variables, but thats just my opinion 😅

**Comment by generall** [comment]
I also don't think ENV should be parsed internally

**Comment by generall** [comment]
Hi @nleroy917, we intercepted your PR a bit https://github.com/qdrant/qdrant_client/pull/99, hope it solves the issue for you!
Please feel free to suggest any other improvements.

**Comment by nleroy917** [comment]
@generall no worries! I was moving too slowly. I'll let you know if I run into other issues...

**Pull request closed without merging**
